/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.resumableBoundaryWalker;

import it.unibo.resumableBoundaryWalker.controller.RobotController;
import it.unibo.resumableBoundaryWalker.gui.AlertManager;
import it.unibo.resumableBoundaryWalker.gui.MainPane;
import it.unibo.resumableBoundaryWalker.supports.NoSuchIssProtocolException;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import javax.websocket.DeploymentException;
import java.io.IOException;
import java.net.URISyntaxException;

public class ResumableBoundaryWalker extends Application {

    private RobotController controller;
    private MainPane mainPane;

    @Override
    public void start(Stage stage) {
        mainPane = new MainPane();
        Scene scene = new Scene(mainPane, 350, 200);
        stage.setTitle("ResumableBoundaryWalker");
        stage.setScene(scene);
        stage.show();

        try {
            controller = new RobotController();
            mainPane.attachController(controller);
        } catch (NoSuchIssProtocolException e) {
            AlertManager.showErrorPopup("IssProtocol Error", e.getClass().getSimpleName(), e.getLocalizedMessage());
            Platform.exit();
        } catch (DeploymentException e) {
            AlertManager.showErrorPopup("WS Error", e.getClass().getSimpleName(), e.getLocalizedMessage());
            Platform.exit();
        } catch (IOException e) {
            AlertManager.showErrorPopup("I/O Error", e.getClass().getSimpleName(), e.getLocalizedMessage());
            Platform.exit();
        } catch (URISyntaxException e) {
            AlertManager.showErrorPopup("Wrong URL", e.getClass().getSimpleName(), e.getLocalizedMessage());
            Platform.exit();
        }
    }

    @Override
    public void stop() {
        try {
           if(controller != null)
               controller.close();
        } catch (IOException e) {
            AlertManager.showErrorPopup("I/O Error", e.getClass().getSimpleName(), e.getLocalizedMessage());
        }
    }

    public static void main(String[] args){
        Application.launch(args);
    }
}
