/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    jacoco
    java
    application
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    flatDir{ dirs("./lib")   }
}

version="1.0"


java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
	 // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")
    
    //OkHttp library for websockets with Kotlin
    implementation( "com.squareup.okhttp3:okhttp:4.9.0" )
    
     // https://mvnrepository.com/artifact/org.json/json
    implementation("org.json:json:20201115" )
    
    //HTTP
    // https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient
    implementation("org.apache.httpcomponents:httpclient:4.5.13")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")
    implementation( "uniboIssSupport:IssWsHttpJavaSupport" )
    implementation( "uniboRobotSpeaker:IssRobotSpeaker" )
}

application {
    // Define the main class for the application.
    mainClass.set("it.unibo.cautiousExplorerActors.MainCautiousRobotActor")
}
