/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.cautiousExplorerActors;

import it.unibo.issRobotSpeaker.CrilRobotSpeaker;
import it.unibo.issRobotSpeaker.RobotSpeaker;
import it.unibo.supports2021.IssWsHttpJavaSupport;

public class MainCautiousRobotActor {
	
	public MainCautiousRobotActor() {
		IssWsHttpJavaSupport support = IssWsHttpJavaSupport.createForWs("localhost:8091");
		RobotSpeaker speaker = CrilRobotSpeaker.newCrilSpeaker();
		
		CautiousExplorerActor cea = new CautiousExplorerActor("cautiousActor", support, speaker);
		support.registerActor(cea);
		cea.send("startApp");
		
		System.out.println("MainCautiousRobotActor | CREATED  n_Threads=" + Thread.activeCount());
	}

    public static void main(String[] args) {
    	 try {
             System.out.println("MainRobotActorJava | main start n_Threads=" + Thread.activeCount());
             new MainCautiousRobotActor();
             //System.out.println("MainRobotActorJava  | appl n_Threads=" + Thread.activeCount());
         } catch ( Exception e) {
             e.printStackTrace();
         }
    }
}
